resources:
- repo: self
  fetchDepth: 15

variables:
- group: a

stages:
- stage: Build_1
  jobs:
  - job: Job_1
    displayName: Phase-1
    condition: succeeded()
    pool:
      name: Default
    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download secure file'
      inputs:
        secureFile: 'a6514fef-2d4e-4c30-a2b7-e1dacb2c1e50'

- stage: Build_2
  jobs:
  - job: Job_1
    displayName: Phase-1
    condition: succeeded()
    pool: Default
    steps:
    - task: AzureAppServiceManage@0
      displayName: 'Restart Azure App Service: ajgsbrtest1app'
      inputs:
        azureSubscription: 'armconn'
        Action: 'Restart Azure App Service'
        WebAppName: ajgtestapp

- stage: PPE
  condition: always()
  jobs:
  - job: Test
    condition: always()
    pool: 'Hosted'
    steps:
    - script: echo 'Hosted'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    condition: always()
    environment: Nikhil-Env08
    pool: 'Hosted'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
