resources:
- repo: self
  fetchDepth: 15

variables:
- group: a

stages:
- stage: Build_1
  jobs:
  - job: Job_1
    displayName: Phase-1
    condition: succeeded()
    pool:
      name: Default
    steps:
    - task: DownloadSecureFile@1
      displayName: 'Download secure file'
      inputs:
        secureFile: '53154311-04fb-489e-8d70-4635a29c6818'

- stage: Build_2
  jobs:
  - job: Job_1
    displayName: Phase-1
    condition: succeeded()
    pool: Default
    steps:
    - task: AzureAppServiceManage@0
      displayName: 'Restart Azure App Service: ajgsbrtest1app'
      inputs:
        azureSubscription: 'armconn'
        Action: 'Restart Azure App Service'
        WebAppName: ajgsbrtest1app

  - job: Job_2
    displayName: Phase-2
    condition: succeededOrFailed()
    pool:
      name: Default
    steps:
    - task: JenkinsDownloadArtifacts@1
      displayName: 'Download artifacts produced by T1'
      inputs:
        jenkinsServerConnection: 'jenkins-new'
        jobName: T1

- stage: PPE
  jobs:
  - job: Test
    pool: 'Hosted'
    steps:
    - script: echo 'Hosted'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    environment: Nikhil-Env08
    pool: 'Hosted'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'
