parameters:
  vgName: ''
  conName: ''

jobs:
  - job: Job_1
    displayName: Phase-1
    condition: succeeded()
    variables:
    - name: _RunAsInternal
      value: False
    - group: ${{ parameters.vgName }}
    pool:
      ${{ if eq(variables._RunAsInternal, False) }}:
        name: Default
      ${{ if eq(variables._RunAsInternal, True) }}:
        name: anraghunpool
    steps:
    - task: AzureAppServiceManage@0
      displayName: 'Restart Azure App Service: ajgsbrtest1app'
      inputs:
        azureSubscription: ${{ parameters.conName }}
        Action: 'Restart Azure App Service'
        WebAppName: ajreactapp
