parameters:
  vgName: ''
  conName: ''

jobs:
  - job: Job_1
    displayName: Phase-1
    condition: succeeded()
    variables:
    - group: ${{ parameters.vgName }}
    pool:
      name: Default
    steps:
    - task: AzureAppServiceManage@0
      displayName: 'Restart Azure App Service: ajgsbrtest1app'
      inputs:
        azureSubscription: ${{ parameters.conName }}
        Action: 'Restart Azure App Service'
        WebAppName: ajreactapp
